# Generated by Django 3.1.7 on 2021-03-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210323_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language'),
        ),
    ]
