# Generated by Django 3.2 on 2022-06-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220512_1848'),
        ('users', '0004_group'),
    ]

    operations = [
    ]
