# Generated by Django 3.2 on 2022-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_status_updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
