# Generated by Django 4.0.5 on 2022-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_active_status_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='see_intro',
            field=models.BooleanField(default=True),
        ),
    ]
