# Generated by Django 4.0.5 on 2022-10-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_see_intro'),
        ('users', '0009_user_student_grade'),
    ]

    operations = [
    ]
