# Generated by Django 4.0.5 on 2023-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_skip_intro_for_assessments'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'supervisor'), name='unique_group_name_per_supervisor'),
        ),
    ]
