# Generated by Django 3.1.7 on 2021-04-06 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0003_auto_20210326_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('valid', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerInput',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('value', models.CharField(max_length=512)),
            ],
            bases=('answers.answer',),
        ),
        migrations.CreateModel(
            name='AnswerNumberLine',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('value', models.IntegerField()),
            ],
            bases=('answers.answer',),
        ),
        migrations.CreateModel(
            name='AssessmentTopicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=True)),
                ('duration', models.DurationField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_topic_answers', to='answers.answersession')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='topic_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.assessmenttopicanswer'),
        ),
        migrations.CreateModel(
            name='AnswerSort',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('category_A', models.ManyToManyField(related_name='answer_category_A', to='assessments.SortOption')),
                ('category_B', models.ManyToManyField(related_name='answer_category_B', to='assessments.SortOption')),
            ],
            bases=('answers.answer',),
        ),
        migrations.CreateModel(
            name='AnswerSelect',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('selected_options', models.ManyToManyField(to='assessments.SelectOption')),
            ],
            bases=('answers.answer',),
        ),
    ]
