# Generated by Django 3.1.7 on 2021-04-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='topic_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.assessmenttopicanswer'),
        ),
        migrations.AddField(
            model_name='answersort',
            name='category_A',
            field=models.ManyToManyField(related_name='answer_category_A', to='assessments.SortOption'),
        ),
        migrations.AddField(
            model_name='answersort',
            name='category_B',
            field=models.ManyToManyField(related_name='answer_category_B', to='assessments.SortOption'),
        ),
        migrations.AddField(
            model_name='answerselect',
            name='selected_options',
            field=models.ManyToManyField(to='assessments.SelectOption'),
        ),
    ]
