# Generated by Django 3.2 on 2021-04-30 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='answersession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='assessmenttopicanswer',
            name='duration',
        ),
        migrations.AddField(
            model_name='answersession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answersession',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessmenttopicanswer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmenttopicanswer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assessmenttopicanswer',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
