# Generated by Django 3.2 on 2021-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_alter_assessment_subject'),
        ('answers', '0003_auto_20210430_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinput',
            name='value',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='answernumberline',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerselect',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='assessments.SelectOption'),
        ),
        migrations.AlterField(
            model_name='answersort',
            name='category_A',
            field=models.ManyToManyField(blank=True, related_name='answer_category_A', to='assessments.SortOption'),
        ),
        migrations.AlterField(
            model_name='answersort',
            name='category_B',
            field=models.ManyToManyField(blank=True, related_name='answer_category_B', to='assessments.SortOption'),
        ),
    ]
