# Generated by Django 3.2 on 2022-05-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_auto_20220426_1727'),
        ('answers', '0005_auto_20210813_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttopicanswer',
            name='topic_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_topic_answers', to='assessments.assessmenttopicaccess'),
        ),
    ]
