# Generated by Django 3.2 on 2022-06-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_auto_20220613_1121'),
        ('answers', '0006_alter_assessmenttopicanswer_topic_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFindHotspot',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('selected_options', models.ManyToManyField(blank=True, to='assessments.AreaOption')),
            ],
            bases=('answers.answer',),
        ),
        migrations.CreateModel(
            name='AnswerDragAndDrop',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.areaoption')),
                ('selected_draggable_options', models.ManyToManyField(blank=True, to='assessments.DraggableOption')),
            ],
            bases=('answers.answer',),
        ),
    ]
