# Generated by Django 3.2 on 2022-06-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_auto_20220512_1848'),
        ('answers', '0006_alter_assessmenttopicanswer_topic_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.question'),
        ),
    ]
