# Generated by Django 3.2 on 2022-06-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0007_alter_answer_question'),
        ('answers', '0007_answerdraganddrop_answerfindhotspot'),
    ]

    operations = [
    ]
