# Generated by Django 4.0.5 on 2022-07-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_merge_20220621_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerDragAndDrop',
        ),
    ]
