# Generated by Django 4.0.5 on 2022-09-22 17:38
# Migration used to createad a new temporary FK relationship before changes M2M relation to FK

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_draggableoption__area_option'),
        ('answers', '0010_answerdraganddrop_draganddropareaentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerselect',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_option', to='assessments.selectoption'),
        ),
        migrations.AddField(
            model_name='draganddropareaentry',
            name='selected_draggable_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_draggable_option', to='assessments.draggableoption'),
        ),
    ]
