# Generated by Django 4.0.5 on 2022-09-22 18:21
# Migration created to change M2M to FK, manually assigning the relationship from the M2M to the FK

from django.db import migrations

class Migration(migrations.Migration):

    def migrate_m2m_to_fk(apps, schema):
        AnswerSelect = apps.get_model('answers', 'AnswerSelect')
        for answer_select in AnswerSelect.objects.all():
            for selected_option in answer_select.selected_options.all():
                answer_select.selected_option = selected_option
                answer_select.save()
        
        DragAndDropAreaEntry = apps.get_model('answers', 'DragAndDropAreaEntry')
        for drag_drop in DragAndDropAreaEntry.objects.all():
            for selected_drag in drag_drop.selected_draggable_options.all():
                drag_drop.selected_draggable_option = selected_drag
                drag_drop.save()

    dependencies = [
        ('answers', '0011_answerselect_selected_option_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_m2m_to_fk)
    ]
