# Generated by Django 4.0.5 on 2022-09-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0012_auto_20220922_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerselect',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='draganddropareaentry',
            name='selected_draggable_options',
        ),
    ]
