# Generated by Django 4.0.5 on 2022-09-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0013_remove_answerselect_selected_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSEL',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('statement', models.CharField(choices=[('NOT_REALLY', 'Not really like me'), ('A_LITTLE', 'A little like me'), ('A_LOT', 'A lot like me')], max_length=32)),
            ],
            bases=('answers.answer',),
        ),
    ]
