# Generated by Django 4.0.5 on 2022-09-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_questiondomino_alter_question_question_type_and_more'),
        ('answers', '0014_answersel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDomino',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('selected_domino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_domino', to='assessments.dominooption')),
            ],
            bases=('answers.answer',),
        ),
    ]
