# Generated by Django 4.0.5 on 2022-11-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0016_answercalcul'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCustomizedDragAndDrop',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('left_value', models.IntegerField()),
                ('right_value', models.IntegerField()),
                ('final_value', models.IntegerField()),
            ],
            bases=('answers.answer',),
        ),
    ]
