# Generated by Django 4.0.5 on 2022-11-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_remove_questionsetaccess_unique_access_per_student_and_topic_and_more'),
        ('answers', '0017_answercustomizeddraganddrop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentTopicAnswer',
            new_name='QuestionSetAnswer',
        ),
    ]
