# Generated by Django 4.0.5 on 2022-11-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_remove_questionsetaccess_unique_access_per_student_and_topic_and_more'),
        ('answers', '0018_rename_assessmenttopicanswer_questionsetanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsetanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set_answers', to='answers.answersession'),
        ),
        migrations.AlterField(
            model_name='questionsetanswer',
            name='topic_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_set_answers', to='assessments.questionsetaccess'),
        ),
    ]
