# Generated by Django 4.0.5 on 2022-11-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0020_rename_topic_access_questionsetanswer_question_set_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='topic_answer',
            new_name='question_set_answer',
        ),
    ]
