# Generated by Django 3.1.7 on 2021-03-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210323_1020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('grade', models.IntegerField()),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('LITERACY', 'Literacy')], max_length=32)),
                ('private', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.IntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('question_type', models.CharField(choices=[('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort')], max_length=32)),
                ('hint', models.CharField(blank=True, max_length=2048, null=True)),
                ('assessment_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttopic')),
            ],
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInput',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('valid_answer', models.CharField(max_length=512)),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='QuestionSelect',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('multiple', models.BooleanField(default=False)),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='QuestionSort',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('category_A', models.CharField(max_length=256)),
                ('category_B', models.CharField(max_length=256)),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('AUDIO', 'Audio'), ('IMAGE', 'Image')], max_length=64)),
                ('link', models.CharField(max_length=2048)),
                ('question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.question')),
                ('select_option_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.selectoption')),
                ('sort_option_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.sortoption')),
            ],
        ),
        migrations.AddField(
            model_name='sortoption',
            name='question_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionsort'),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='question_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionselect'),
        ),
    ]
