# Generated by Django 3.2 on 2021-04-10 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('grade', models.IntegerField()),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('LITERACY', 'Literacy')], max_length=32)),
                ('private', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.IntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('question_type', models.CharField(choices=[('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('NUMBER_LINE', 'Number line')], max_length=32)),
                ('assessment_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttopic')),
            ],
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInput',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('valid_answer', models.CharField(max_length=512)),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='QuestionNumberLine',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('expected_value', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('step', models.IntegerField()),
                ('show_ticks', models.BooleanField()),
                ('show_value', models.BooleanField()),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='QuestionSelect',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('multiple', models.BooleanField(default=False)),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='QuestionSort',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('category_A', models.CharField(max_length=256)),
                ('category_B', models.CharField(max_length=256)),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('AUDIO', 'Audio'), ('IMAGE', 'Image')], max_length=64)),
                ('link', models.CharField(max_length=2048)),
                ('hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.hint')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.question')),
                ('select_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.selectoption')),
                ('sort_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.sortoption')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTopicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttopic')),
            ],
            options={
                'verbose_name_plural': 'Assessment topics access',
            },
        ),
        migrations.AddField(
            model_name='sortoption',
            name='question_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionsort'),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='question_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionselect'),
        ),
    ]
