# Generated by Django 3.2 on 2021-04-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectoption',
            name='question_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.questionselect'),
        ),
        migrations.AlterField(
            model_name='sortoption',
            name='question_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.questionsort'),
        ),
    ]
