# Generated by Django 3.1.7 on 2021-03-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20210325_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionNumberLine',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('expected_value', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('step', models.IntegerField()),
                ('show_ticks', models.BooleanField()),
                ('show_value', models.BooleanField()),
            ],
            bases=('assessments.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('NUMBER_LINE', 'Number line')], max_length=32),
        ),
    ]
