# Generated by Django 3.2 on 2021-04-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20210412_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hint', to='assessments.question'),
        ),
    ]
