# Generated by Django 3.2 on 2021-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_hint_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnumberline',
            name='show_ticks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnumberline',
            name='show_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='assessmenttopic',
            constraint=models.UniqueConstraint(fields=('order', 'assessment'), name='unique_order'),
        ),
    ]
