# Generated by Django 3.2 on 2021-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20210413_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttopicaccess',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttopicaccess',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
