# Generated by Django 3.2 on 2021-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_auto_20210414_1255'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assessmenttopicaccess',
            constraint=models.UniqueConstraint(fields=('student', 'topic'), name='unique_access_per_student_and_topic'),
        ),
    ]
