# Generated by Django 3.2 on 2021-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_auto_20210422_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allow_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='show_feedback',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Always'), (2, 'Second attempt on')], default=2),
        ),
    ]
