# Generated by Django 3.2 on 2021-05-13 08:04

import django.core.validators
from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Question = apps.get_model('assessments', 'Question')
    for question in Question.objects.all().iterator():
        question.order = question.id
        question.save()

def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any

class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_auto_20210428_1044'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmenttopic',
            name='unique_order',
        ),
        migrations.RemoveField(
            model_name='assessmenttopic',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='hint',
            name='text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='selectoption',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sortoption',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('order', 'assessment_topic'), name='unique_order'),
        ),
    ]
