# Generated by Django 3.2 on 2021-05-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessmenttopic_evaluated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='allow_skip',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='show_feedback',
        ),
        migrations.AddField(
            model_name='assessmenttopic',
            name='allow_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmenttopic',
            name='show_feedback',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Always'), (2, 'Second attempt on')], default=2),
        ),
    ]
