# Generated by Django 3.2 on 2021-06-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_auto_20210531_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='link',
        ),
    ]
