# Generated by Django 3.2 on 2021-06-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_auto_20210531_1401'),
        ('assessments', '0011_remove_attachment_link'),
    ]

    operations = [
    ]
