# Generated by Django 3.2 on 2021-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_alter_assessment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttopic',
            name='praise',
            field=models.IntegerField(default=0),
        ),
    ]
