# Generated by Django 3.2 on 2021-06-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_assessmenttopic_praise'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttopic',
            name='max_wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
