# Generated by Django 3.2 on 2021-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_assessmenttopic_max_wrong_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='icon',
            field=models.FileField(null=True, upload_to='assessments_icons'),
        ),
        migrations.AddField(
            model_name='assessmenttopic',
            name='icon',
            field=models.FileField(null=True, upload_to='topics_icons'),
        ),
    ]
