# Generated by Django 3.2 on 2021-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_assessmenttopic_max_wrong_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionselect',
            name='displayType',
            field=models.CharField(choices=[('GRID', 'Grid'), ('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical')], default='GRID', max_length=32),
        ),
    ]
