# Generated by Django 3.2 on 2021-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_auto_20210719_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='assessments_icons'),
        ),
        migrations.AlterField(
            model_name='assessmenttopic',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='topics_icons'),
        ),
    ]
