# Generated by Django 3.2 on 2021-07-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_questionselect_displaytype'),
        ('assessments', '0017_auto_20210720_0845'),
    ]

    operations = [
    ]
