# Generated by Django 3.2 on 2021-07-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_rename_displaytype_questionselect_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Math'), ('LITERACY', 'Literacy'), ('PRESEL', 'PreSel'), ('POSTSEL', 'PostSel'), ('TUTORIAL', 'Tutorial')], max_length=32),
        ),
    ]
