# Generated by Django 3.2 on 2021-08-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_alter_assessment_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
