# Generated by Django 3.2 on 2021-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='identifier',
            field=models.CharField(default='question-identifier', max_length=256),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='identifier',
            field=models.CharField(default='select-option-identifier', max_length=256),
        ),
    ]
