# Generated by Django 3.2 on 2021-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_auto_20210928_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.CharField(default='question-identifier-missing', max_length=256),
        ),
        migrations.AlterField(
            model_name='selectoption',
            name='identifier',
            field=models.CharField(default='select-option-identifier-missing', max_length=256),
        ),
    ]
