# Generated by Django 3.2 on 2022-04-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_auto_20211006_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortoption',
            old_name='value',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.CharField(default='question-value-missing', max_length=256, null=False),
        ),
        migrations.RenameField(
            model_name='question',
            old_name='identifier',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='selectoption',
            old_name='value',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='selectoption',
            name='identifier',
            field=models.CharField(default='select-option-value-missing', max_length=256, null=True),
        ),
        migrations.RenameField(
            model_name='selectoption',
            old_name='identifier',
            new_name='value',
        ),
    ]
