# Generated by Django 3.2 on 2022-05-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220512_1848'),
        ('assessments', '0026_auto_20220426_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.language'),
        ),
    ]
