# Generated by Django 4.0.5 on 2022-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_auto_20220512_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='downloadable',
            field=models.BooleanField(default=True),
        ),
    ]
