# Generated by Django 3.2 on 2022-06-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_auto_20220512_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDragAndDrop',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
            ],
            bases=('assessments.question',),
        ),
        migrations.CreateModel(
            name='QuestionFindHotspot',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
            ],
            bases=('assessments.question',),
        ),
        migrations.AddField(
            model_name='attachment',
            name='background_image',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('NUMBER_LINE', 'Number line'), ('DRAG_AND_DROP', 'Drag and Drop'), ('FIND_HOTSPOT', 'Find hotspot')], max_length=32),
        ),
        migrations.CreateModel(
            name='DraggableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_option', models.ManyToManyField(blank=True, related_name='areas', to='assessments.AreaOption')),
                ('question_drag_and_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_options', to='assessments.questiondraganddrop')),
            ],
        ),
        migrations.AddField(
            model_name='areaoption',
            name='question_drag_and_drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_areas', to='assessments.questiondraganddrop'),
        ),
        migrations.AddField(
            model_name='areaoption',
            name='question_find_hotspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_areas', to='assessments.questionfindhotspot'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='draggable_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.draggableoption'),
        ),
    ]
