# Generated by Django 4.0.5 on 2022-07-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_assessment_downloadable'),
        ('assessments', '0028_auto_20220613_1121'),
    ]

    operations = [
    ]
