# Generated by Django 4.0.5 on 2022-07-06 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_merge_20220704_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenttopic',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='assessmenttopic',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
