# Generated by Django 4.0.5 on 2022-07-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_assessment_downloadable'),
        ('assessments', '0029_question_on_popup'),
    ]

    operations = [
    ]
