# Generated by Django 4.0.5 on 2022-07-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_alter_assessmenttopic_options_assessmenttopic_order'),
        ('assessments', '0030_merge_20220711_1516'),
    ]

    operations = [
    ]
