# Generated by Django 4.0.5 on 2022-07-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_merge_20220712_1734'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_order',
        ),
    ]
