# Generated by Django 4.0.5 on 2022-08-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_merge_20220714_1508'),
        ('assessments', '0032_remove_question_unique_order'),
    ]

    operations = [
    ]
