# Generated by Django 4.0.5 on 2022-09-22 17:38
# Migration used to createad a new temporary FK relationship before changes M2M relation to FK

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0034_assessmenttopic_subtopic_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='draggableoption',
            name='_area_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_areas', to='assessments.areaoption'),
        ),
    ]
