# Generated by Django 4.0.5 on 2022-09-22 17:41
# Migration created to change M2M to FK, manually assigning the relationship from the M2M to the FK

from django.db import migrations

def migrate_m2m_to_fk(apps, schema):
    DraggableOption = apps.get_model('assessments', 'DraggableOption')
    for drag_option in DraggableOption.objects.all():
        for area_option in drag_option.area_option.all():
            drag_option._area_option = area_option
            drag_option.save()

class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_draggableoption__area_option'),
    ]

    operations = [
        migrations.RunPython(migrate_m2m_to_fk)
    ]
