# Generated by Django 4.0.5 on 2022-09-26 12:10
# Migration created to remove all, but the first, valid Select Option from Questions Select

from django.db import migrations

def remove_multiple_valid_answers(apps, schema):
    QuestionSelect = apps.get_model('assessments', 'QuestionSelect')
    SelectOption = apps.get_model('assessments', 'SelectOption')
    questions = QuestionSelect.objects.all()
    for question in questions:
        sliced_queryset = SelectOption.objects.filter(question_select=question,valid=True)[1:]
        SelectOption.objects.filter(id__in=sliced_queryset).update(valid=False)

class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0037_remove_draggableoption__area_option_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_multiple_valid_answers)
    ]
