# Generated by Django 4.0.5 on 2022-09-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0038_auto_20220926_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSEL',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
            ],
            bases=('assessments.question',),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sel_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Difficulty 1'), (2, 'Difficulty 2'), (3, 'Difficulty 3')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SEL', 'Social and Emotional Learning'), ('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('NUMBER_LINE', 'Number line'), ('DRAG_AND_DROP', 'Drag and Drop'), ('FIND_HOTSPOT', 'Find hotspot')], max_length=32),
        ),
    ]
