# Generated by Django 4.0.5 on 2022-10-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_questionsel_assessment_sel_question_and_more'),
        ('assessments', '0039_remove_questionnumberline_show_ticks_and_more'),
    ]

    operations = [
    ]
