# Generated by Django 4.0.5 on 2022-09-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_questionsel_assessment_sel_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDomino',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('expected_value', models.IntegerField()),
            ],
            bases=('assessments.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SEL', 'Social and Emotional Learning'), ('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('DOMINO', 'Domino'), ('NUMBER_LINE', 'Number line'), ('DRAG_AND_DROP', 'Drag and Drop'), ('FIND_HOTSPOT', 'Find hotspot')], max_length=32),
        ),
        migrations.CreateModel(
            name='DominoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side_value', models.IntegerField()),
                ('right_side_value', models.IntegerField()),
                ('valid', models.BooleanField()),
                ('question_domino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.questiondomino')),
            ],
        ),
    ]
