# Generated by Django 4.0.5 on 2022-10-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_merge_20221007_1102'),
        ('assessments', '0040_questiondomino_alter_question_question_type_and_more'),
    ]

    operations = [
    ]
