# Generated by Django 4.0.5 on 2022-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_merge_20221010_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnumberline',
            name='shuffle',
            field=models.BooleanField(default=False),
        ),
    ]
