# Generated by Django 4.0.5 on 2022-10-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_merge_20221010_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCalcul',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('first_value', models.IntegerField()),
                ('second_value', models.IntegerField()),
                ('operator', models.CharField(choices=[('ADDITION', 'Addition'), ('SUBTRACTION', 'Subtraction'), ('DIVISION', 'Division'), ('MULTIPLICATION', 'Multiplication')], max_length=32)),
            ],
            bases=('assessments.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SEL', 'Social and Emotional Learning'), ('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('DOMINO', 'Domino'), ('NUMBER_LINE', 'Number line'), ('DRAG_AND_DROP', 'Drag and Drop'), ('CALCUL', 'Calcul'), ('FIND_HOTSPOT', 'Find hotspot')], max_length=32),
        ),
    ]
