# Generated by Django 4.0.5 on 2022-10-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_questionnumberline_shuffle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('LITERACY', 'Literacy'), ('PRESEL', 'PreSel'), ('POSTSEL', 'PostSel'), ('TUTORIAL', 'Tutorial')], max_length=32)),
                ('name', models.CharField(max_length=62)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=32)),
                ('name_eng', models.CharField(default='', max_length=255)),
                ('name_ara', models.CharField(default='', max_length=255)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.subtopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='assessmenttopic',
            name='subtopic'
        ),
        migrations.AddField(
            model_name='assessmenttopic',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.subtopic'),
        ),
    ]
