# Generated by Django 4.0.5 on 2022-11-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_questioncalcul_alter_question_question_type'),
        ('assessments', '0044_remove_question_difficulty_and_more'),
    ]

    operations = [
    ]
