# Generated by Django 4.0.5 on 2022-11-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_merge_20221107_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCustomizedDragAndDrop',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.question')),
                ('first_value', models.IntegerField()),
                ('first_color', models.CharField(choices=[('RED', 'Red'), ('LIGHT_GREEN', 'Light Green'), ('DARK_GREEN', 'Dark Green'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('LIGHT_BLUE', 'Light Blue'), ('DARK_BLUE', 'Dark Blue'), ('PINK', 'Pink'), ('PURPLE', 'Purple')], max_length=32)),
                ('second_value', models.IntegerField()),
                ('second_color', models.CharField(choices=[('RED', 'Red'), ('LIGHT_GREEN', 'Light Green'), ('DARK_GREEN', 'Dark Green'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('LIGHT_BLUE', 'Light Blue'), ('DARK_BLUE', 'Dark Blue'), ('PINK', 'Pink'), ('PURPLE', 'Purple')], max_length=32)),
                ('operator', models.CharField(choices=[('ADDITION', 'Addition'), ('SUBTRACTION', 'Subtraction'), ('DIVISION', 'Division'), ('MULTIPLICATION', 'Multiplication')], max_length=32)),
                ('item', models.CharField(choices=[('PENCIL', 'pencil'), ('FRUIT', 'fruit'), ('BALLON', 'ballon'), ('BUTTON', 'button'), ('SOCKS', 'socks'), ('PAINT', 'paint')], max_length=32)),
            ],
            bases=('assessments.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SEL', 'Social and Emotional Learning'), ('INPUT', 'Input'), ('SELECT', 'Select'), ('SORT', 'Sort'), ('DOMINO', 'Domino'), ('NUMBER_LINE', 'Number line'), ('DRAG_AND_DROP', 'Drag and Drop'), ('CUSTOMIZED_DRAG_AND_DROP', 'Customized Drag and Drop'), ('CALCUL', 'Calcul'), ('FIND_HOTSPOT', 'Find hotspot')], max_length=32),
        ),
    ]
