# Generated by Django 4.0.5 on 2022-11-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0046_numberrange_question_number_range'),
        ('assessments', '0046_questioncustomizeddraganddrop_and_more'),
    ]

    operations = [
    ]
