# Generated by Django 4.0.5 on 2022-11-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0047_merge_20221130_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttopic',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='learning_objective',
        ),
        migrations.AddField(
            model_name='assessment',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.subtopic'),
        ),
        migrations.AddField(
            model_name='assessmenttopic',
            name='learning_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.learningobjective'),
        ),
    ]
