# Generated by Django 4.0.5 on 2022-12-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0047_merge_20221130_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='on_popup',
        ),
    ]
