# Generated by Django 4.0.5 on 2022-12-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0048_remove_assessmenttopic_subtopic_and_more'),
        ('assessments', '0048_remove_question_on_popup'),
    ]

    operations = [
    ]
