# Generated by Django 4.0.5 on 2022-11-29 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0016_answercalcul'),
        ('assessments', '0050_rename_assessmenttopic_questionset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentTopicAccess',
            new_name='QuestionSetAccess',
        ),
        migrations.AlterModelOptions(
            name='questionsetaccess',
            options={'verbose_name_plural': 'Set of questions accesses'},
        ),
    ]
