# Generated by Django 4.0.5 on 2022-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0051_rename_assessmenttopicaccess_questionsetaccess_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionsetaccess',
            name='unique_access_per_student_and_topic',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='topic',
            new_name='question_set',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='assessment_topic',
            new_name='question_set',
        ),
        migrations.RenameField(
            model_name='questionsetaccess',
            old_name='topic',
            new_name='question_set',
        ),
        migrations.AddConstraint(
            model_name='questionsetaccess',
            constraint=models.UniqueConstraint(fields=('student', 'question_set'), name='unique_access_per_student_and_question_set'),
        ),
    ]
