# Generated by Django 4.0.5 on 2022-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_rename_subtopic_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='question_sets_icons'),
        ),
    ]
