# Generated by Django 4.0.5 on 2022-12-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0054_alter_questionset_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='allow_skip',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='max_wrong_answers',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='praise',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='show_feedback',
        ),
    ]
