# Generated by Django 4.0.5 on 2022-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0055_remove_questionset_allow_skip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionselect',
            name='show_options_value',
            field=models.BooleanField(default=False),
        ),
    ]
