# Generated by Django 4.0.5 on 2022-12-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0050_question_created_at_question_updated_at'),
        ('assessments', '0056_questionselect_show_options_value'),
    ]

    operations = [
    ]
