# Generated by Django 4.0.5 on 2022-12-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0058_alter_question_created_at_alter_question_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionselect',
            name='show_options_value',
        ),
        migrations.AddField(
            model_name='questionselect',
            name='show_options_title',
            field=models.BooleanField(default=True),
        ),
    ]
