# Generated by Django 4.0.5 on 2022-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0059_remove_questionselect_show_options_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnumberline',
            name='shuffle',
        ),
        migrations.AddField(
            model_name='question',
            name='shuffle',
            field=models.BooleanField(default=False),
        ),
    ]
