# Generated by Django 3.2 on 2021-05-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccompetency',
            options={'verbose_name_plural': 'Topic competencies'},
        ),
    ]
