# Generated by Django 3.2 on 2021-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20210628_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
