# Generated by Django 3.2 on 2021-06-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_remove_profile_avatars_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.avatar')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatars_collection',
            field=models.ManyToManyField(through='gamification.Selected', to='gamification.Avatar'),
        ),
    ]
