# Generated by Django 3.2 on 2021-06-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_auto_20210628_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selected',
            new_name='Unlocked',
        ),
        migrations.AlterModelOptions(
            name='unlocked',
            options={'verbose_name_plural': 'Unlocked'},
        ),
    ]
