# Generated by Django 3.2 on 2021-06-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20210628_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatars_collection',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_on_profile', to='gamification.avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unlocked_avatars',
            field=models.ManyToManyField(to='gamification.Avatar'),
        ),
        migrations.DeleteModel(
            name='Unlocked',
        ),
    ]
