# Generated by Django 3.2 on 2021-06-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_auto_20210629_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unlocked_avatars',
            field=models.ManyToManyField(related_name='unlocked_on_profile', to='gamification.Avatar'),
        ),
    ]
