# Generated by Django 3.2 on 2021-07-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_alter_profile_unlocked_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='name',
        ),
    ]
