# Generated by Django 3.2 on 2021-07-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_remove_avatar_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ['effort_cost']},
        ),
    ]
