# Generated by Django 4.0.5 on 2022-11-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_alter_avatar_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiccompetency',
            old_name='topic',
            new_name='question_set',
        ),
    ]
